server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      mode: always
      schema-locations: classpath:db/migration/schema.sql
      data-locations: classpath:db/data/data.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher