package com.example.dynamic_menu_builder.util;

import java.io.PrintWriter;
import java.io.StringWriter;


public class ExceptionUtils {
    /**
     * Gets the stack trace from a Throwable as a String.
     *
     * @param throwable the <code>Throwable</code> to be examined
     * @return the stack trace as generated by the exception's
     * <code>printStackTrace(PrintWriter)</code> method
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }
}
